title: MineRL Project
description: >- # this means to ignore newlines until "baseurl:"
  Reinforcement learning is the name of the game.
baseurl: "" # the subpath of your site, e.g. /blog
url: test.minerl.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - download-site.sh
   - update.sh
   - test.sh
   - .gitignore
   - README.md

highlighter: rouge


titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
