title: MineRL Project
description: >- # this means to ignore newlines until "baseurl:"
  Reinforcement learning is the name of the game.
baseurl: "" # the subpath of your site, e.g. /blog
url: "test.minerl.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - download-site.sh
   - update.sh
   - test.sh
   - build.sh
   - .gitignore
   - README.md
include:
  # Sadly, this doesn't seem to be enough to get docs to work
  # with test.sh. These directories are copied over into _site
  # for some reason. We solve this by manually copying over the
  # docs directory into _site, like `update.sh` and `build.sh`.
  #
  # See README.md for special instructions on testing Sphinx docs
  # locally.
  - docs/_sites/
  - docs/_images/

highlighter: rouge

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

permalink: /:categories/:title/
permalink: pretty
collections:
    categories:
        output: true
